[setting] blue-green

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -59,15 +59,50 @@ jobs:
     runs-on: self-hosted
 
     steps:
-      - name: docker pull
-        run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/testone:latest
+      - name: Set target IP
+        run: |
+          STATUS=$(curl -o /dev/null -w "%{http_code} https://${{secrets.LIVE_SERVER_IP}}/env")
+          echo $STATUS
+          if [ "$STATUS" = "200" ]; then
+            CURRENT_UPSTREAM=$(curl -s "http://${{secrets.LIVE_SERVER_IP}}/env")
+          else
+            CURRENT_UPSTREAM=green
+          fi
+          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
+          if [ "$CURRENT_UPSTREAM" = "blue" ]; then
+            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+          elif [ "$CURRENT_UPSTREAM" = "green" ]; then
+            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+          else
+            echo "error"
+            exit 1
+          fi
 
-      - name: docker stop container
-        run: sudo docker stop $(sudo docker ps -q) 2>dev/null || true
+      #- name: docker pull
+        #run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/testone:latest
 
-      - name: docker run new container
-        run: sudo docker run --rm -d -p 8080:8080 ${{secrets.DOCKER_USERNAME}}/testone:latest
+      - name: docker compose
+        run: sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d --build
 
-      - name: delete old docker image
-        run: sudo docker system prune -f
+      - name: Change nginx upstram
+        run: |
+          echo "set \$service_url ${{env.TARGET_UPSTREAM}};" | sudo tee /etc/nginx/conf.d/service-env.inc
+          sudo nginx -s reload
+
+      - name: Stop docker container
+        run: |
+          sudo docker stop ${{env.CURRENT_UPSTREAM}}
+          sudo docker rm ${{env.CURRENT_UPSTREAM}}
+          
+
+     # - name: docker run new container
+      #  run: |
+       #   sudo docker-compose -f docker-compose-green.yml up -d --build
+
+      #- name: delete old docker image
+       # run: sudo docker system prune -f
       
